<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateKategorisTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('kategoris', function(Blueprint $table)
		{
			$table->increments('id');
			$table->integer('id_induk');
			$table->integer('id_jenis');
			$table->string('name');
			$table->integer('image');
			$table->string('status');
			$table->string('description');
			$table->timestamps();
		});

		for ($i=1930; $i <= date("Y"); $i++) { 
			$x = new \App\Kategori;
			$x->id_induk = 0;
			$x->id_jenis = \App\JKategori::where('code','year')->first()['id'];
			$x->name = $i;
			$x->image = 0;
			$x->status = 'active';
			$x->description = 'Category Year '.$i;
			$x->save();
		} 
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','condition')->first()['id'];
		$x->name = 'New';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Condition New';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','condition')->first()['id'];
		$x->name = 'Second';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Condition Second';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','vehicle_mileage')->first()['id'];
		$x->name = 1000;
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Vehicle Mileage 1000';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','vehicle_mileage')->first()['id'];
		$x->name = 5000;
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Vehicle Mileage 5000';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','vehicle_mileage')->first()['id'];
		$x->name = 15000;
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Vehicle Mileage 15000';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','vehicle_mileage')->first()['id'];
		$x->name = 35000;
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Vehicle Mileage 35000';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','vehicle_mileage')->first()['id'];
		$x->name = 50000;
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Vehicle Mileage 50000';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','vehicle_mileage')->first()['id'];
		$x->name = 75000;
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Vehicle Mileage 75000';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','vehicle_mileage')->first()['id'];
		$x->name = 100000;
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Vehicle Mileage 100000';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','vehicle_mileage')->first()['id'];
		$x->name = 150000;
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Vehicle Mileage 150000';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','engine_size')->first()['id'];
		$x->name = 'less than 150';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Engine Size less than 150';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','engine_size')->first()['id'];
		$x->name = 'less than 250';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Engine Size less than 250';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','engine_size')->first()['id'];
		$x->name = 'less than 500';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Engine Size less than 500';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','engine_size')->first()['id'];
		$x->name = 'less than 1000';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Engine Size less than 1000';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','engine_size')->first()['id'];
		$x->name = 'Over 1000';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Engine Size Over 1000';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','for_sale_by')->first()['id'];
		$x->name = 'Dealer';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category For Sale by Dealer';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','for_sale_by')->first()['id'];
		$x->name = 'Private Seller';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category For Sale by Private Seller';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','exterior_color')->first()['id'];
		$x->name = 'Black';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Exterior Color Black';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','exterior_color')->first()['id'];
		$x->name = 'Blue';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Exterior Color Blue';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','exterior_color')->first()['id'];
		$x->name = 'White';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Exterior Color White';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','exterior_color')->first()['id'];
		$x->name = 'Red';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Exterior Color Red';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','exterior_color')->first()['id'];
		$x->name = 'Green';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Exterior Color Green';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','exterior_color')->first()['id'];
		$x->name = 'Yellow';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Exterior Color Yellow';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','exterior_color')->first()['id'];
		$x->name = 'Orange';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Exterior Color Orange';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','exterior_color')->first()['id'];
		$x->name = 'Grey';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Exterior Color Grey';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','part')->first()['id'];
		$x->name = 'Exhaust';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Part Exhaust';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','part')->first()['id'];
		$x->name = 'Brakes';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Part Brakes';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','part')->first()['id'];
		$x->name = 'Wheels';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Part Wheels';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','part')->first()['id'];
		$x->name = 'Suspension';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Part Suspension';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','part')->first()['id'];
		$x->name = 'Lamps';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Part Lamps';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','part')->first()['id'];
		$x->name = 'Engine';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Part Engine';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','part')->first()['id'];
		$x->name = 'Apparel';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Part Apparel';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = 0;
		$x->id_jenis = \App\JKategori::where('code','part')->first()['id'];
		$x->name = 'Other Accessories';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Part Other Accessories';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Pilar::where('code','motorcycles_pilar')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','make')->first()['id'];
		$x->name = 'Harley Davidson';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Make Harley Davidson';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Pilar::where('code','motorcycles_pilar')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','make')->first()['id'];
		$x->name = 'Honda';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Make Honda';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Pilar::where('code','motorcycles_pilar')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','make')->first()['id'];
		$x->name = 'Kawasaki';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Make Kawasaki';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Pilar::where('code','motorcycles_pilar')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','make')->first()['id'];
		$x->name = 'Yamaha';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Make Yamaha';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Pilar::where('code','motorcycles_pilar')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','make')->first()['id'];
		$x->name = 'Suzuki';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Make Suzuki';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Pilar::where('code','cars_pilar')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','make')->first()['id'];
		$x->name = 'BMW';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Make BMW';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Pilar::where('code','cars_pilar')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','make')->first()['id'];
		$x->name = 'Honda';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Make Honda';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Pilar::where('code','cars_pilar')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','make')->first()['id'];
		$x->name = 'Mitsubishi';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Make Mitsubishi';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Pilar::where('code','cars_pilar')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','make')->first()['id'];
		$x->name = 'Suzuki';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Make Suzuki';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Kategori::where('id_induk',\App\Pilar::where('code','motorcycles_pilar')->first()['id'])->where('name','Honda')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','model')->first()['id'];
		$x->name = 'CB150R';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Model CB150R';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Kategori::where('id_induk',\App\Pilar::where('code','motorcycles_pilar')->first()['id'])->where('name','Honda')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','model')->first()['id'];
		$x->name = 'CBR150R';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Model CBR150R';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Kategori::where('id_induk',\App\Pilar::where('code','motorcycles_pilar')->first()['id'])->where('name','Honda')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','model')->first()['id'];
		$x->name = 'CBR250RR';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Model CBR250RR';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Kategori::where('id_induk',\App\Pilar::where('code','cars_pilar')->first()['id'])->where('name','BMW')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','model')->first()['id'];
		$x->name = 'X1';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Model X1';
		$x->save();
		$x = new \App\Kategori;
		$x->id_induk = \App\Kategori::where('id_induk',\App\Pilar::where('code','cars_pilar')->first()['id'])->where('name','BMW')->first()['id'];
		$x->id_jenis = \App\JKategori::where('code','model')->first()['id'];
		$x->name = 'M5 Sedan';
		$x->image = 0;
		$x->status = 'active';
		$x->description = 'Category Model M5 Sedan';
		$x->save();
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('kategoris');
	}

}
